module.exports = [
	'.as', '.mxml',
	'.ada', '.adb', '.ads',
	'.asm', '.s',
	'.asp',
	'.master', '.ascx', '.asmx', '.aspx', '.svc',
	'.bat', '.cmd',
	'.c', '.h', '.xs',
	'.cfc', '.cfm', '.cfml',
	'.clj',
	'.txt', '.cmake',
	'.coffee',
	'.cpp', '.cc', '.cxx', '.m', '.hpp', '.hh', '.h', '.hxx',
	'.cs',
	'.css',
	'.dart',
	'.pas', '.int', '.dfm', '.nfm', '.dof', '.dpk', '.dproj', '.groupproj', '.bdsgroup', '.bdsproj',
	'.el',
	'.ex', '.exs',
	'.erl', '.hrl',
	'.f', '.f77', '.f90', '.f95', '.f03', '.for', '.ftn', '.fpp',
	'go',
	'.groovy', '.gtmpl', '.gpp', '.grunit', '.gradle',
	'.hs', '.lhs',
	'.h',
	'.htm', '.html',
	'.java', '.properties',
	'.js',
	'.json',
	'.jsp', '.jspx', '.jhtm', '.jhtml',
	'.less',
	'.lisp', '.lsp',
	'.lua',
	'.mk', '.mak',
	'.m',
	'.mkd', '.md',
	'.m', '.h',
	'.mm', '.h',
	'.ml', '.mli',
	'.pir', '.pasm', '.pmc', '.ops', '.pod', '.pg', '.tg',
	'.pl', '.pm',
	'.t',
	'.php', '.phpt', '.php3', '.php4', '.php5', '.phtml',
	'.pt', '.cpt', '.metadata', '.cpy', '.py',
	'.pmc',
	'.py ',
	'Rakefile',
	'.R',
	'.rb', '.rhtml', '.rjs', '.rxml', '.erb', '.rake', '.spec',
	'.rs',
	'.sass', '.scss',
	'.scala',
	'.scm', '.ss',
	'.sh', '.bash', '.csh', '.tcsh', '.ksh', '.zsh', '.fish',
	'.st',
	'.sql', '.ctl',
	'.tcl', '.itcl', '.itk',
	'.tex', '.cls', '.sty',
	'.textile',
	'.tt', '.tt2', '.ttml',
	'.bas', '.cls', '.frm', '.ctl', '.vb', '.resx',
	'.v', '.vh', '.sv',
	'.vhd', '.vhdl',
	'.vim',
	'.xml', '.dtd', '.xsl', '.xslt', '.ent',
	'.yaml', '.yml'
];
